version: "3"

services:
  s1:
    image: yandex/clickhouse-server
    ports:
      - "9001:9000"
    volumes:
      - "./config.xml:/etc/clickhouse-server/conf.d/config.xml:ro"
  s2:
    image: yandex/clickhouse-server
    ports:
      - "9002:9000"
    volumes:
      - "./config.xml:/etc/clickhouse-server/conf.d/config.xml:ro"
